# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

schedules:
- cron: "* * * * *"
  displayName: cron
  branches:
    include:
    - main
  always: false
  
pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run in-line script'

- script: |
    python main.py
  displayName: 'Run a python script'
